sillsdev/machine

src/SIL.Machine.AspNetCore/Services/LocalStorage.cs, src/SIL.Machine.AspNetCore/Services/ThotSmtModelFactory.cs, src/SIL.Machine.Translation.Thot/ThotSmtModelTrainer.cs, src/SIL.Machine/Utils/DirectoryHelper.cs, src/SIL.Machine/Utils/TempDirectory.cs, tests/SIL.Machine.Tokenization.SentencePiece.Tests/SentencePieceTokenizerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/59)
=> #58 - centralize and make directory deleting more robust

src/SIL.Machine.AspNetCore/Services/SmtTransferEngineBuildJob.cs
Opted to explicitly pass CancellationToken.None rather than leaving default for consistency with other code and added clarity.
Fixes Cancellation token - inconsistent SMT training state #62
--ECL
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/71)
=> Removed cancellation token passing after line 99.

.gitignore, src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs, src/SIL.Machine.AspNetCore/SIL.Machine.AspNetCore.csproj, src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs, src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs, src/SIL.Machine.AspNetCore/Services/ClearMLService.cs, src/SIL.Machine.AspNetCore/Services/IClearMLAuthenticationService.cs, src/SIL.Machine.AspNetCore/Usings.cs, src/SIL.Machine.Serval.EngineServer/appsettings.Development.json, src/SIL.Machine.Serval.EngineServer/appsettings.json, tests/SIL.Machine.AspNetCore.Tests/Services/ClearMLServiceTests.cs
Also relevant to #50. 
* Used Polly to auto-retry
* Refactored `ClearMLAuthenticationService` a bit to avoid issue where token wasn't properly populating immediately
* Small fixes in the `ClearMLHealthCheck` and to logging
* (Added ".history" to the gitignore - vs code extension generates files in this folder on my box and, I presume, others)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/66)
=> Fixes ClearML server is down - and then hangfire crashes #65 --ECL

src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs, src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs, src/SIL.Machine.AspNetCore/Services/TranslationEngineServiceBase.cs, src/SIL.Machine.AspNetCore/Utils/EngineNotBuiltException.cs, tests/SIL.Machine.AspNetCore.Tests/Services/SmtTransferEngineServiceTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/82)
=> Fixes Throw error for unbuilt engine #81

src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs, src/SIL.Machine.AspNetCore/Configuration/IServiceCollectionExtensions.cs, src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs, src/SIL.Machine.AspNetCore/Services/ClearMLService.cs, src/SIL.Machine.AspNetCore/Services/IClearMLService.cs, src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs, src/SIL.Machine.AspNetCore/Services/S3HealthCheck.cs
Change interval of health checks to 4 minutes.
S3 pings up to three times before returning Unhealthy.
(Also, removed redundant logging)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/85)
=> Fixes S3 bucket unecessary alerts

src/SIL.Machine.Morphology.HermitCrab/MorphologicalRules/AffixProcessAllomorph.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/87)
=> Required features on allomorphs should use subsumption

src/SIL.Machine.AspNetCore/SIL.Machine.AspNetCore.csproj, src/SIL.Machine.Serval.EngineServer/Program.cs, src/SIL.Machine.Serval.EngineServer/SIL.Machine.Serval.EngineServer.csproj, src/SIL.Machine.Serval.JobServer/Program.cs, src/SIL.Machine.Serval.JobServer/SIL.Machine.Serval.JobServer.csproj
Fixes https://github.com/sillsdev/serval/issues/58
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/88)
=> Added open telemetry instrumentation

src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs, src/SIL.Machine.AspNetCore/Usings.cs
If there is no target file, there are no target refs; in this case, use the source ref.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/94)
=> Fixes RefId's don't get populated for Paratext Projects #93

src/SIL.Machine.AspNetCore/Configuration/ClearMLOptions.cs, src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs, src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs, src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs, src/SIL.Machine.AspNetCore/Services/ClearMLService.cs, src/SIL.Machine.Serval.EngineServer/Program.cs, src/SIL.Machine.Serval.EngineServer/appsettings.json, src/SIL.Machine.Serval.JobServer/Program.cs, src/SIL.Machine.Serval.JobServer/appsettings.json, tests/SIL.Machine.AspNetCore.Tests/SIL.Machine.AspNetCore.Tests.csproj, tests/SIL.Machine.AspNetCore.Tests/Services/ClearMLServiceTests.cs
- move ClearML connection string to "ConnectionStrings" section
- fixes #108
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/115)
=> Use named HTTP clients for ClearML

src/SIL.Machine.AspNetCore/Services/NmtEngineService.cs, src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs
Add more detailed error message to exception thrown when attempting to start a build while a build is currently building or being canceled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/117)
=> Fixes https://github.com/sillsdev/serval/issues/121

src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs, src/SIL.Machine.AspNetCore/Services/ClearMLService.cs, src/SIL.Machine.AspNetCore/Services/IClearMLService.cs
This solution fetches all tasks queued in the configured queue and unions them with the tasks associated with currently monitored translation engines. This means that there are two additional API calls per `ClearMLMonitorService` run (one to fetch the ids of tasks on the queue and another to fetch the complete info on those tasks). I think this is inevitable because the get-all-queues call only contains information about queued jobs (and, if you dig, currently running jobs), but not jobs that may have failed or completed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/124)
=> Fixes #118

src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs, src/SIL.Machine.AspNetCore/Usings.cs, tests/SIL.Machine.AspNetCore.Tests/Services/LanguageTagServiceTests.cs
Refactor for some edge cases and for cleaner understanding of what is going on.
This should align with the documentation at https://github.com/sillsdev/serval/wiki/Language-Tag-Resolution-for-NLLB%E2%80%90200.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/126)
=> Update language code parsing

src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs, src/SIL.Machine.AspNetCore/Services/CancellationInterceptor.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/134)
=> Fixes #130

src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs, src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs, src/SIL.Machine.AspNetCore/Services/S3HealthCheck.cs
Implemented same logic in ClearML as in S3.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/135)
=> Fixes #133

src/SIL.Machine.Tool/CorpusCommandSpecBase.cs, src/SIL.Machine.Tool/ParallelCorpusCommandSpec.cs, src/SIL.Machine.Translation.Thot/SIL.Machine.Translation.Thot.csproj, src/SIL.Machine.Translation.Thot/Thot.cs, src/SIL.Machine.Translation.Thot/ThotSmtModel.cs, tests/SIL.Machine.Translation.Thot.Tests/ThotFastAlignWordAlignmentModelTests.cs, tests/SIL.Machine.Translation.Thot.Tests/ThotSmtModelTests.cs
- fixes #131
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/138)
=> Correctly handle corrupt SMT models

src/SIL.Machine.AspNetCore/Services/CancellationInterceptor.cs
Returning a null response from a gRPC `Interceptor` is not allowed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/140)
=> Fix null reference return error

src/SIL.Machine/Translation/FuzzyEditDistanceWordAlignmentMethod.cs, tests/SIL.Machine.Tests/Translation/FuzzyEditDistanceWordAlignmentMethodTests.cs
- fixes #145
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/146)
=> Fix NaN alignment score in FuzzyEditDistanceWordAlignmentMethod

src/SIL.Machine.AspNetCore/Services/ClearMLService.cs, src/SIL.Machine.AspNetCore/Usings.cs, src/SIL.Machine.AspNetCore/Utils/CustomEnumConverterFactory.cs
Fixes https://github.com/sillsdev/serval/issues/236
Opened: https://github.com/sillsdev/machine/issues/149
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/150)
=> Revert to using CustomEnumConverter

src/SIL.Machine/Corpora/UsfmParser.cs, src/SIL.Machine/Corpora/UsfmTextBase.cs, src/SIL.Machine/Corpora/UsfmToken.cs, src/SIL.Machine/Corpora/UsfmTokenizer.cs, tests/SIL.Machine.Tests/Corpora/CorporaTestHelpers.cs, tests/SIL.Machine.Tests/Corpora/TestData/.gitattributes, tests/SIL.Machine.Tests/Corpora/TestData/usfm/Tes/41MATTes.SFM, tests/SIL.Machine.Tests/Corpora/UsfmFileTextTests.cs, tests/SIL.Machine.Tests/Corpora/UsfmTokenizerTests.cs
- closes #153
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/154)
=> Add support for detokenizing USFM

src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs, tests/SIL.Machine.AspNetCore.Tests/Services/NmtEngineServiceTests.cs, tests/SIL.Machine.AspNetCore.Tests/Services/NmtPreprocessBuildJobTests.cs
This is to support https://github.com/sillsdev/machine/issues/152, logging builds in Loki for metrics and aggregation.
Parallel pull request here: https://github.com/sillsdev/serval/pull/263
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/155)
=> Build log output

src/SIL.Machine.AspNetCore/Services/NmtClearMLBuildJobFactory.cs, tests/SIL.Machine.AspNetCore.Tests/Services/NmtClearMLBuildJobFactoryTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/157)
=> Passed shared file folder to ClearML NMT job

src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs, src/SIL.Machine/Corpora/CorporaExtensions.cs, src/SIL.Machine/Corpora/ParallelTextCorpus.cs, tests/SIL.Machine.Tests/Corpora/CorporaExtensionsTests.cs
When creating a `ParallelTextCorpus`, if target has no references, make target references source references changed to target versification.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/169)
=> Move logic to parallel text corpus

.editorconfig, src/SIL.Machine.AspNetCore/Models/Build.cs, src/SIL.Machine.AspNetCore/Models/ClearMLMetricsEvent.cs, src/SIL.Machine.AspNetCore/Models/ClearMLProject.cs, src/SIL.Machine.AspNetCore/Models/ClearMLTask.cs, src/SIL.Machine.AspNetCore/Models/Corpus.cs, src/SIL.Machine.AspNetCore/Models/CorpusFile.cs, src/SIL.Machine.AspNetCore/Models/Lock.cs, src/SIL.Machine.AspNetCore/Models/ModelDownloadUrl.cs, src/SIL.Machine.AspNetCore/Models/Pretranslation.cs, src/SIL.Machine.AspNetCore/Models/RWLock.cs, src/SIL.Machine.AspNetCore/Models/TrainSegmentPair.cs, src/SIL.Machine.AspNetCore/Models/TranslationEngine.cs, src/SIL.Machine.AspNetCore/SIL.Machine.AspNetCore.csproj, src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs, src/SIL.Machine.AspNetCore/Services/DistributedReaderWriterLockFactory.cs, src/SIL.Machine.AspNetCore/Services/InMemoryStorage.cs, src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs, src/SIL.Machine.AspNetCore/Services/LocalStorage.cs, src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs, src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs, src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs, src/SIL.Machine.AspNetCore/Usings.cs, src/SIL.Machine.AspNetCore/Utils/AsyncDisposableBase.cs, tests/SIL.Machine.AspNetCore.Tests/Services/DistributedReaderWriterLockFactoryTests.cs, tests/SIL.Machine.AspNetCore.Tests/Services/NmtClearMLBuildJobFactoryTests.cs, tests/SIL.Machine.AspNetCore.Tests/Services/NmtEngineServiceTests.cs, tests/SIL.Machine.AspNetCore.Tests/Services/NmtPreprocessBuildJobTests.cs, tests/SIL.Machine.AspNetCore.Tests/Services/SmtTransferEngineServiceTests.cs, tests/SIL.Machine.AspNetCore.Tests/Usings.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/172)
=> Refactor models to records

src/SIL.Machine.AspNetCore/Models/ClearMLTask.cs, src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs
All of these properties are technically optional according to the docs. Should we make them all not required? It seems like we might want to avoid processing tasks that, for example, don't have an ID (And I'm not sure how that would ever happen anyways).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/176)
=> Remove required property from optional ClearMLTask attributes

src/AssemblyInfo.props
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/183)
=> Update machine version

src/SIL.Machine/Scripture/ScriptureRangeParser.cs, tests/SIL.Machine.Tests/Scripture/ScriptureRangeParserTests.cs
Fix mis-parsing of chapter selections when book name ends in a digit
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/187)
=> Fixes https://github.com/sillsdev/serval/issues/365

.gitignore, .vscode/extensions.json, .vscode/settings.json, .vscode/tasks.json, src/SIL.Machine/Corpora/ScriptureRef.cs, tests/SIL.Machine.AspNetCore.Tests/SIL.Machine.AspNetCore.Tests.csproj, tests/SIL.Machine.Morphology.HermitCrab.Tests/SIL.Machine.Morphology.HermitCrab.Tests.csproj, tests/SIL.Machine.Tests/Corpora/ScriptureRefTests.cs, tests/SIL.Machine.Tests/SIL.Machine.Tests.csproj, tests/SIL.Machine.Tokenization.SentencePiece.Tests/SIL.Machine.Tokenization.SentencePiece.Tests.csproj, tests/SIL.Machine.Translation.Thot.Tests/SIL.Machine.Translation.Thot.Tests.csproj
https://github.com/sillsdev/machine/issues/181
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/182)
=> Test coverage

src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs, src/SIL.Machine/Corpora/UsfmTextUpdater.cs, tests/SIL.Machine.AspNetCore.Tests/Services/NmtPreprocessBuildJobTests.cs, tests/SIL.Machine.Tests/Corpora/TestData/usfm/Tes/41MATTes.SFM, tests/SIL.Machine.Tests/Corpora/UsfmFileTextTests.cs, tests/SIL.Machine.Tests/Corpora/UsfmTextUpdaterTests.cs, tests/SIL.Machine.Tests/Corpora/UsfmTokenizerTests.cs
https://github.com/sillsdev/serval/issues/370
Reworked the logic of preferring existing or new text.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/189)
=> Control the pretranslation of existing text

.gitignore, src/SIL.Machine/Corpora/ScriptureRefUsfmParserHandlerBase.cs, tests/SIL.Machine.Tests/Corpora/CorporaTestHelpers.cs, tests/SIL.Machine.Tests/Corpora/TestData/usfm/Tes/41MATTes.SFM, tests/SIL.Machine.Tests/Corpora/UsfmFileTextTests.cs, tests/SIL.Machine.Tests/Corpora/UsfmParserTests.cs, tests/SIL.Machine.Tests/Corpora/UsfmTokenizerTests.cs
Fixes:
https://github.com/sillsdev/serval/issues/376
https://github.com/sillsdev/serval/issues/375
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/191)
=> Usfm parse error logging

src/SIL.Machine/Corpora/ScriptureRefUsfmParserHandlerBase.cs, tests/SIL.Machine.Tests/Corpora/TestData/usfm/Tes/41MATTes.SFM, tests/SIL.Machine.Tests/Corpora/UsfmTokenizerTests.cs, tests/SIL.Machine.Tests/Scripture/ScriptureRangeParserTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/198)
=> Fix crash when parsing duplicate verses separated by a paragraph marker

src/SIL.Machine/Corpora/ScriptureElement.cs, src/SIL.Machine/Corpora/ScriptureRefUsfmParserHandlerBase.cs, tests/SIL.Machine.Tests/Corpora/TestData/usfm/Tes/41MATTes.SFM, tests/SIL.Machine.Tests/Corpora/UsfmFileTextTests.cs, tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs, tests/SIL.Machine.Tests/Corpora/UsfmTextUpdaterTests.cs, tests/SIL.Machine.Tests/Corpora/UsfmTokenizerTests.cs
- fixes https://github.com/sillsdev/serval/issues/388
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/201)
=> Fix exception when parsing USFM with an empty verse paragraph

src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs, tests/SIL.Machine.AspNetCore.Tests/Services/NmtPreprocessBuildJobTests.cs
Fixes https://github.com/sillsdev/serval/issues/284
A couple questions regarding the solution:
1. I noticed that John has it throwing an `OperationCanceledException` when the engine doesn't exist in `NmtPreprocessBuildJob`. Is that what we want? Or should this throw some other exception that would cause the build to be marked as failed instead? And if so, should it also do the same in this case? Maybe I'm missing something. 
2. I thought I'd add a test to cover the logic mentioned above, but it seems to be unreachable because if the engine does not exist, it'll get cut short here in the `HangfireBuildJob` code:  
`if (!await BuildJobService.BuildJobStartedAsync(engineId, buildId, cancellationToken))
{
completionStatus = JobCompletionStatus.Canceled;
return;
}`
What am I missing?
- - - …
=> Throw error when both languages are unknown and there's no data

src/SIL.Machine/Corpora/ScriptureElement.cs, src/SIL.Machine/Corpora/ScriptureRef.cs, src/SIL.Machine/Corpora/UsfmTextUpdater.cs, tests/SIL.Machine.Tests/Corpora/ScriptureRefTests.cs, tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs, tests/SIL.Machine.Tests/Corpora/UsfmTextUpdaterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/204)
=> Correctly implement relaxed comparison for UsfmTextUpdater

src/SIL.Machine/Corpora/ScriptureRefUsfmParserHandlerBase.cs, src/SIL.Machine/Corpora/UsfmTokenizer.cs, tests/SIL.Machine.Tests/Corpora/TestData/usfm/Tes/41MATTes.SFM, tests/SIL.Machine.Tests/Corpora/UsfmTokenizerTests.cs
- fixes https://github.com/sillsdev/serval/issues/393
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/203)
=> Ignore a note that occurs right after \id marker

.ignore, src/SIL.Machine/Corpora/ScriptureRefUsfmParserHandlerBase.cs, src/SIL.Machine/Corpora/UsfmParser.cs, src/SIL.Machine/Corpora/UsfmParserState.cs, src/SIL.Machine/Corpora/UsfmTextBase.cs, src/SIL.Machine/Corpora/UsfmToken.cs, src/SIL.Machine/Corpora/UsfmTokenizer.cs, tests/SIL.Machine.Tests/Corpora/TestData/usfm/Tes/41MATTes.SFM, tests/SIL.Machine.Tests/Corpora/UsfmFileTextTests.cs, tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs, tests/SIL.Machine.Tests/Corpora/UsfmTokenizerTests.cs
Make USFM updating errors more explicit: https://github.com/sillsdev/serval/issues/398
@ddaspit  - can up finish resolving the USFM updating parse stack empty issue?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/206)
=> Recreate the USFM text updating issue in unit tests.

src/SIL.Machine/Corpora/ParatextBackupTermsCorpus.cs
Fixes https://github.com/sillsdev/serval/issues/391
Fixes https://github.com/sillsdev/serval/issues/392
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/208)
=> Fix terms bugs

src/AssemblyInfo.props
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/210)
=> Update library to version 3.2.0

src/SIL.Machine.AspNetCore/Models/Corpus.cs, src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs, src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs, tests/SIL.Machine.AspNetCore.Tests/Services/NmtPreprocessBuildJobTests.cs, tests/SIL.Machine.AspNetCore.Tests/Services/SmtTransferEngineServiceTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/209)
=> Clarify and fix logic for textId and Chapters.

src/SIL.Machine/Corpora/MemoryStreamContainer.cs, src/SIL.Machine/Corpora/ScriptureRefUsfmParserHandlerBase.cs, src/SIL.Machine/Corpora/UsfmMemoryText.cs, tests/SIL.Machine.Tests/Corpora/CorporaTestHelpers.cs, tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs, tests/SIL.Machine.Tests/Corpora/UsfmTextUpdaterTests.cs
- fixes https://github.com/sillsdev/serval/issues/416
- add UsfmMemoryText for testing
- add support for isolated testing of USFM parsing/generation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/216)
=> Remove obsolete handling of \d marker

src/SIL.Machine/Corpora/UsfmTextUpdater.cs, tests/SIL.Machine.Tests/Corpora/UsfmTextUpdaterTests.cs
https://github.com/sillsdev/serval/issues/411
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/214)
=> Fix 2, 2a, 2b verse merging

.ignore, src/SIL.Machine/Corpora/UsfmTextBase.cs, tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs
https://github.com/sillsdev/serval/issues/424
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/222)
=> correctly parse table in duplicate verse

tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs
Addresses https://github.com/sillsdev/serval/issues/429
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/227)
=> Extend manual test to process multiple projects including zipped projects

src/SIL.Machine/Corpora/ScriptureRefUsfmParserHandlerBase.cs, src/SIL.Machine/Corpora/UsfmTextBase.cs, tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs
I'm not sure that this is the cleanest solution, but it does resolve the issue. Please critique :)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/232)
=> Fixes https://github.com/sillsdev/serval/issues/449

tests/SIL.Machine.Tests/Corpora/ParatextProjectTermsParserTests.cs
Matthew brought to my attention in his porting that there were some tests that became duplicates of each other after changes to the options regarding using glosses.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/237)
=> Remove duplicate test

README.md
#238
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/239)
=> Remove ApiServer Readme

src/SIL.Machine/Corpora/UsfmTextBase.cs, tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs
- fixes #242
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/243)
=> Ignore opt break that occurs outside of a segment

src/SIL.Machine/FiniteState/Fst.cs
This is just the fix proposed by Andy for https://jira.sil.org/browse/LT-20351.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/248)
=> Fix original LT-20351

src/SIL.Machine/Corpora/ParatextBackupTermsCorpus.cs, src/SIL.Machine/Corpora/ParatextProjectTermsParserBase.cs, tests/SIL.Machine.Tests/Corpora/ParatextProjectTermsParserTests.cs
Addresses https://github.com/sillsdev/serval/issues/476
Supports https://github.com/sillsdev/serval/pull/508
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/256)
=> Add parameter for filtering key terms by book/chapters

src/SIL.Machine/Utils/EnumerableExtensions.cs, tests/SIL.Machine.Tests/Utils/EnumberableExtensionTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/257)
=> If there are no enumerators, it enters an infinite loop.

src/SIL.Machine.Morphology.HermitCrab/Morpher.cs
Beth reported that the novel root guesser couldn't handle homographs (e.g. two lexical entries that looked like [Seg]*).  This was because there was code to suppress duplicate paths through a pattern, but the scope was too big.  Narrowing the scope fixed the problem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/259)
=> LT-21911: Fix problem that suppressed homographs

src/SIL.Machine/Corpora/ParallelTextCorpus.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/260)
=> Fix forever loop

src/SIL.Machine/Corpora/ParatextProjectTextUpdaterBase.cs, src/SIL.Machine/Corpora/UpdateUsfmParserHandler.cs, tests/SIL.Machine.Tests/Corpora/UpdateUsfmParserHandlerTests.cs, tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs
This will require a corresponding change in Serval.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/263)
=> Refactor stripAllText and preferExistingText into a single enum

src/SIL.Machine.Morphology.HermitCrab/AnalysisStratumRule.cs, tests/SIL.Machine.Morphology.HermitCrab.Tests/HermitCrabTestBase.cs, tests/SIL.Machine.Morphology.HermitCrab.Tests/MorpherTests.cs
There was a bug in AnalysisStratumRule.Apply when the MorphologicalRuleOrder was Linear.  It did not include the case where there were morphological rules but no templates.  This did not match what SynthesisStratumRule.Apply was doing.  I fixed the bug and extended a unit test to cover this case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/279)
=> Fix bug with MorphologicalRuleOrder.Linear for LT-21988

src/SIL.Machine.Morphology.HermitCrab/AnalysisStratumRule.cs, tests/SIL.Machine.Morphology.HermitCrab.Tests/MorpherTests.cs
There was a bug in how unapplication worked for morphological rules with MorphologicalRuleOrder.Linear.  I created a test case that provoked the bug, and then I fixed the bug by using PermutationRuleOrder instead of LinearRuleOrder.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/280)
=> Fix another bug with MorphologicalRuleOrder.Linear

src/SIL.Machine.Morphology.HermitCrab/AnalysisStratumRule.cs, src/SIL.Machine.Morphology.HermitCrab/Morpher.cs, src/SIL.Machine.Morphology.HermitCrab/Word.cs
This merges equivalent analyses in AnalysisStratumRule.Apply and then expands alternatives after they have been found in the lexicon in Morpher.  This can speed things up by 3-4x if there are multiple strata since fewer analyses get passed from one stratum to the next.  It required adding a Source field and an Alternatives field to Word so that the alternatives can be reconstructed by Word.ExpandAlternatives.  The Source field gets filled in with the original word when a Word is cloned so that past alternatives can be accessed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/282)
=> Merge duplicate analyses

src/SIL.Machine.Morphology.HermitCrab/Word.cs
ExpandAlternatives didn't work correctly with realizational rules.  I didn't notice this before because ExpandAlternatives treated originals.Count == 1 as a special case, and bypassed the code for reconstructing the alternative starting at line 423.  Disabling the special case code caused the RealizationRule unit test to fail.  All of the unit tests work now, but if you can think of anything else the code for reconstructing the alternative should include, please let me know.  Ideally, the code for reconstruction would figure out what changes were made between Source and this, and then apply those changes to the alternative. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machi …
=> Fix bug with realizational rules

src/SIL.Machine/Corpora/ParatextProjectTextUpdaterBase.cs, src/SIL.Machine/Corpora/ScriptureRefUsfmParserHandlerBase.cs, src/SIL.Machine/Corpora/UpdateUsfmParserHandler.cs, src/SIL.Machine/Corpora/UsfmStylesheet.cs, src/SIL.Machine/Corpora/UsfmTextBase.cs, tests/SIL.Machine.Tests/Corpora/TestData/usfm/Tes/41MATTes.SFM, tests/SIL.Machine.Tests/Corpora/UpdateUsfmParserHandlerTests.cs, tests/SIL.Machine.Tests/Corpora/UsfmFileTextTests.cs, tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs, tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs, tests/SIL.Machine.Tests/Corpora/UsfmTokenizerTests.cs
This attempts to address the following issues:
* https://github.com/sillsdev/serval/issues/577
* https://github.com/sillsdev/serval/issues/574
It also reworks the Note handling, making it so that it preserves the reference fields.
It also combines Notes, Figures and Cross References as "SubComponents"
There are still a few tests that need fixed.
There are significant parsing updates - and the tests were updated to match the updated behavior.  @ddaspit - can you check to see if they are going in the right direction?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/281)
=> Do not translate markers

src/SIL.Machine/Corpora/NParallelTextCorpus.cs, tests/SIL.Machine.Tests/Corpora/NParallelTextCorpusTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/290)
=> Bug in NParallelTextCorpus

src/SIL.Machine/Corpora/ParatextProjectTextUpdaterBase.cs, src/SIL.Machine/Corpora/ScriptureRefUsfmParserHandlerBase.cs, src/SIL.Machine/Corpora/UpdateUsfmParserHandler.cs, tests/SIL.Machine.Tests/Corpora/UpdateUsfmParserHandlerTests.cs
Add tests for beginning-of-verse embeds
Fix the embed at beginning issue (https://github.com/sillsdev/serval/issues/636)
Add paragraph marker control (https://github.com/sillsdev/serval/issues/627)
Always preserve \r and \rem
Correct behavior for stripping text behavior (https://github.com/sillsdev/serval/issues/629)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/291)
=> Updates to USFM updater

src/SIL.Machine/Corpora/NParallelTextCorpus.cs, tests/SIL.Machine.Tests/Corpora/ParallelTextCorpusTests.cs
Fixes https://github.com/sillsdev/machine/issues/294
This was a bug that already existed in the previous `ParallelTextCorpus` implementation. We were relying on segment count as an indicator of a new range starting when we should just have used the `IsRangeStart` property since this isn't reliable when your target is totally empty.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/295)
=> Fix faulty edge-case logic in NParallelTextCorpus

src/SIL.Machine/Corpora/UpdateUsfmParserHandler.cs, tests/SIL.Machine.Tests/Corpora/UpdateUsfmParserHandlerTests.cs
Fixes `\rem` not being preserved and similar.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/299)
=> Fix PreserveParagraphStyles

.github/workflows/ci.yml, src/SIL.Machine/FiniteState/DeterministicFsaTraversalMethod.cs, src/SIL.Machine/FiniteState/DeterministicFstTraversalMethod.cs, src/SIL.Machine/FiniteState/NondeterministicFsaTraversalMethod.cs, src/SIL.Machine/FiniteState/NondeterministicFstTraversalMethod.cs, src/SIL.Machine/FiniteState/TraversalMethodBase.cs, src/SIL.Machine/Matching/GroupCapture.cs, src/SIL.Machine/Matching/Match.cs, src/SIL.Machine/Matching/Matcher.cs, src/SIL.Machine/Rules/BatchPatternRuleSpec.cs, tests/SIL.Machine.Morphology.HermitCrab.Tests/PhonologicalRules/RewriteRuleTests.cs, tests/SIL.Machine.Tests/Matching/MatcherTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/298)
=> Add support for patterns that accept empty data

src/SIL.Machine/Corpora/ParatextProjectTextUpdaterBase.cs, src/SIL.Machine/Corpora/UpdateUsfmParserHandler.cs
Partially addresses https://github.com/sillsdev/serval/issues/542
This needs to be merged and a new version of Machine needs to be released before the [Serval PR](https://github.com/sillsdev/serval/pull/681) can be merged.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/301)
=> Add ability to add remarks

src/SIL.Machine/Corpora/ParatextProjectTextUpdaterBase.cs, src/SIL.Machine/Corpora/ScriptureRefUsfmParserHandlerBase.cs, src/SIL.Machine/Corpora/UpdateUsfmParserHandler.cs, src/SIL.Machine/Corpora/UsfmParserState.cs, src/SIL.Machine/Corpora/UsfmTextBase.cs, src/SIL.Machine/Corpora/UsfmUpdateBlock.cs, src/SIL.Machine/Corpora/UsfmUpdateBlockElement.cs, src/SIL.Machine/Corpora/UsfmUpdateBlockHandler.cs, tests/SIL.Machine.Tests/Corpora/UpdateUsfmParserHandlerTests.cs, tests/SIL.Machine.Tests/Corpora/UsfmFileTextTests.cs, tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs
Port of changes [here](https://github.com/sillsdev/machine.py/pull/168).
Fixes https://github.com/sillsdev/serval/issues/667
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/305)
=> Port update block

src/SIL.Machine.Morphology.HermitCrab/AnalysisStratumRule.cs, src/SIL.Machine.Morphology.HermitCrab/CompileException.cs
I wrapped exceptions in the Hermit Crab compiler so that the user would know which rule couldn't be compiled.  This may allow the user to fix the rule causing the problem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/307)
=> Improve error handling for Hermit Crab users

src/SIL.Machine/Corpora/PlaceMarkersUsfmUpdateBlockHandler.cs, src/SIL.Machine/Corpora/UpdateUsfmParserHandler.cs, src/SIL.Machine/Corpora/UsfmParserState.cs, src/SIL.Machine/Corpora/UsfmTextBase.cs, src/SIL.Machine/Corpora/UsfmUpdateBlock.cs, src/SIL.Machine/Corpora/UsfmUpdateBlockElement.cs, tests/SIL.Machine.Tests/Corpora/PlaceMarkersUsfmUpdateBlockHandlerTests.cs, tests/SIL.Machine.Tests/Corpora/UpdateUsfmParserHandlerTests.cs, tests/SIL.Machine.Tests/Corpora/UsfmFileTextTests.cs, tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs
@ddaspit, when porting this, is speed a concern? I've tried to follow machine.py as closely as possible with few exceptions, but there's definitely room for optimization. Is this something we should think about now or just something we should revisit later on?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/306)
=> Port block handler

src/SIL.Machine/Corpora/NParallelTextCorpus.cs, tests/SIL.Machine.Tests/Corpora/ParallelTextCorpusTests.cs
Fixes https://github.com/sillsdev/serval/issues/725
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/323)
=> Use default refs for empty non-scripture rows in NParallelTextCorpus

src/SIL.Machine/PunctuationAnalysis/QuotationMarkFinder.cs, src/SIL.Machine/PunctuationAnalysis/TextSegment.cs, tests/SIL.Machine.Tests/Corpora/CorporaTestHelpers.cs, tests/SIL.Machine.Tests/Corpora/UsfmManualTests.cs, tests/SIL.Machine.Tests/PunctuationAnalysis/QuotationMarkFinderTests.cs, tests/SIL.Machine.Tests/PunctuationAnalysis/TextSegmentTests.cs
Fixes https://github.com/sillsdev/machine/issues/324
* Consistently use text elements for indexing and string length
* Add manual test for running quote convention analysis
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/325)
=> Fix starting element error when analyzing corpora

src/SIL.Machine/PunctuationAnalysis/QuotationMarkFinder.cs, src/SIL.Machine/PunctuationAnalysis/QuotationMarkStringMatch.cs, src/SIL.Machine/PunctuationAnalysis/TextSegment.cs, tests/SIL.Machine.Tests/PunctuationAnalysis/QuotationMarkFinderTests.cs, tests/SIL.Machine.Tests/PunctuationAnalysis/QuotationMarkStringMatchTests.cs, tests/SIL.Machine.Tests/PunctuationAnalysis/TextSegmentTests.cs
Connected to https://github.com/sillsdev/machine.py/pull/228
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/335)
=> Add test to specifically cover surrogate pairs, not just combining characters

src/SIL.Machine/Corpora/FileParatextProjectSettingsParser.cs, tests/SIL.Machine.Tests/Corpora/FileParatextProjectSettingsParserTests.cs, tests/SIL.Machine.Tests/Corpora/TestData/usfm/Tes/custom.sty, tests/SIL.Machine.Tests/Corpora/ZipParatextProjectSettingsParserTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/336)
=> Use correct filename for custom stylesheet

src/SIL.Machine/Corpora/IUsfmUpdateBlockHandler.cs, src/SIL.Machine/Corpora/PlaceMarkersUsfmUpdateBlockHandler.cs, src/SIL.Machine/Corpora/UpdateUsfmParserHandler.cs, src/SIL.Machine/Corpora/UsfmUpdateBlockHandler.cs
Fixes https://github.com/sillsdev/serval/issues/764 and fixes https://github.com/sillsdev/machine/issues/332
* Add custom exception
* Add error handler
* Fix mis-ported lines
As I began coding, I realized that the idea of 'error handler' wasn't concrete enough - there are a number of places and ways we could inject an error handler. We could also design this exception a couple different ways. This is all to say, please say 'That's not at all what I was thinking', @ddaspit, if that's the case :laughing:. I figured it was simpler just to put in the PR and discuss here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/342)
=> Add update block error handling

src/SIL.Machine/Corpora/ParatextProjectTextUpdaterBase.cs, src/SIL.Machine/Corpora/ScriptureRef.cs, src/SIL.Machine/Corpora/ScriptureRefComparer.cs, src/SIL.Machine/Corpora/ScriptureRefUsfmParserHandlerBase.cs, src/SIL.Machine/Corpora/UpdateUsfmParserHandler.cs, src/SIL.Machine/Corpora/VerseRefComparer.cs, tests/SIL.Machine.Tests/Corpora/PlaceMarkersUsfmUpdateBlockHandlerTests.cs, tests/SIL.Machine.Tests/Corpora/UpdateUsfmParserHandlerTests.cs
Fixes https://github.com/sillsdev/machine.py/issues/232
Also fixes https://github.com/sillsdev/machine/issues/339 and fixes https://github.com/sillsdev/machine/issues/340
These will all need to be ported.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/341)
=> Get update rows by reference
