sillsdev/machine

- scripts/data_scraper.py
- scripts/test.sh
- scripts/train.sh
`train.sh` and `test.sh` scripts that assumed the existence of certain directories that are now created if not present. Added a `data_scraper.py` that converts `test.sh` output into `.csv` files.
> Andrew QoL Improvements

- src/SIL.Machine.AspNetCore/SIL.Machine.AspNetCore.csproj
- src/SIL.Machine.AspNetCore/Services/ClearMLService.cs
- src/SIL.Machine.AspNetCore/Usings.cs
- tests/SIL.Machine.AspNetCore.Tests/SIL.Machine.AspNetCore.Tests.csproj
- tests/SIL.Machine.AspNetCore.Tests/Services/ClearMLServiceTests.cs
- tests/SIL.Machine.AspNetCore.Tests/Usings.cs
- closes #37
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/38)
> Convert language tag to NLLB language code

- src/SIL.Machine.AspNetCore/SIL.Machine.AspNetCore.csproj
- src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs
- src/SIL.Machine.AspNetCore/Services/IPlatformService.cs
- src/SIL.Machine.AspNetCore/Services/ServalPlatformService.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/41)
> Update Serval.Grpc to 0.8.0

- dockerfile
- dockerfile.development
- src/SIL.Machine.AspNetCore/SIL.Machine.AspNetCore.csproj
- src/SIL.Machine.AspNetCore/Services/DistributedReaderWriterLock.cs
- src/SIL.Machine.Serval.EngineServer/SIL.Machine.Serval.EngineServer.csproj
- src/SIL.Machine.Serval.JobServer/SIL.Machine.Serval.JobServer.csproj
- src/SIL.Machine/SIL.Machine.csproj
Workaround for #42 :
* revert to ubuntu focal
* add gcc for libdl.so
* Update to SIL.WritingSystems that fixes libdl.so issue
make dockerfile for docker-compose from serval
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/43)
> Docker and k8s updates

- .vscode/settings.json
- src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs
- src/SIL.Machine.AspNetCore/Services/ClearMLService.cs
- src/SIL.Machine.AspNetCore/Services/IClearMLService.cs
- src/SIL.Machine.AspNetCore/Services/ISharedFileService.cs
- src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs
- src/SIL.Machine.AspNetCore/Services/SharedFileService.cs
- tests/SIL.Machine.AspNetCore.Tests/Services/ClearMLNmtEngineServiceTests.cs
- tests/SIL.Machine.AspNetCore.Tests/Services/ClearMLServiceTests.cs
- see https://github.com/sillsdev/serval/issues/29
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/44)
> Enable a non-root S3 bucket path

- src/SIL.Machine.Serval.JobServer/appsettings.Development.json
- src/SIL.Machine.Serval.JobServer/appsettings.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/57)
> Fixes #82 --ECL

- src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs
- fixes #67
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/68)
> Fix configuration of translation Engines

- src/SIL.Machine.AspNetCore/Services/DistributedReaderWriterLock.cs
- src/SIL.Machine.AspNetCore/Services/DistributedReaderWriterLockFactory.cs
- src/SIL.Machine.AspNetCore/Services/IDistributedReaderWriterLockFactory.cs
- src/SIL.Machine.AspNetCore/Services/SmtTransferEngineBuildJob.cs
- src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs
- src/SIL.Machine.AspNetCore/Services/SmtTransferEngineStateService.cs
- src/SIL.Machine.AspNetCore/Services/TranslationEngineServiceBase.cs
- tests/SIL.Machine.AspNetCore.Tests/Services/DistributedReaderWriterLockTests.cs
- tests/SIL.Machine.AspNetCore.Tests/Services/SmtTransferEngineServiceTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/69)
> Simplify distributed lock creation

- src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs
- src/SIL.Machine.AspNetCore/Services/TranslationEngineServiceBase.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/72)
> Fixes https://github.com/sillsdev/serval/issues/95 --ECL

- src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs
[sillsdev/serval#115](https://github.com/sillsdev/serval/issues/115)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/74)
> Fix - still fail job even with S3 bucket failures

- src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/76)
> #75 - don't fail nmt job on delete failing

- src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/79)
> Fix from review #78

- src/SIL.Machine.AspNetCore/Models/ClearMLTask.cs
- src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs
Fixes https://github.com/sillsdev/serval/issues/67
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/86)
> Pass through error message from machine.py

- src/SIL.Machine.Serval.EngineServer/Program.cs
- src/SIL.Machine.Serval.JobServer/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/90)
> Hide console exporter

- src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs
Fixes #97
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/98)
> Added queue name to ClearML health check failure message

- src/SIL.Machine.AspNetCore/Configuration/ClearMLOptions.cs
- src/SIL.Machine.AspNetCore/Services/ClearMLBuildJobRunner.cs
- src/SIL.Machine.AspNetCore/Services/ClearMLService.cs
- src/SIL.Machine.Serval.EngineServer/appsettings.Development.json
- src/SIL.Machine.Serval.EngineServer/appsettings.json
- src/SIL.Machine.Serval.JobServer/appsettings.Development.json
- src/SIL.Machine.Serval.JobServer/appsettings.json
- create a ClearML project if it doesn't exist
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/106)
> Add ClearML Project setting

- src/SIL.Machine.AspNetCore/Configuration/ClearMLOptions.cs
- src/SIL.Machine.AspNetCore/Models/Build.cs
- src/SIL.Machine.AspNetCore/SIL.Machine.AspNetCore.csproj
- src/SIL.Machine.AspNetCore/Services/BuildJobService.cs
- src/SIL.Machine.AspNetCore/Services/ClearMLBuildJobRunner.cs
- src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs
- src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs
- src/SIL.Machine.AspNetCore/Services/ClearMLService.cs
- src/SIL.Machine.AspNetCore/Services/HangfireBuildJob.cs
- src/SIL.Machine.AspNetCore/Services/HangfireBuildJobRunner.cs
- src/SIL.Machine.AspNetCore/Services/IBuildJobRunner.cs
- src/SIL.Machine.AspNetCore/Services/IBuildJobService.cs
- src/SIL.Machine.AspNetCore/Services/IClearMLBuildJobFactory.cs
- src/SIL.Machine.AspNetCore/Services/IHangfireBuildJobFactory.cs
- src/SIL.Machine.AspNetCore/Services/ITranslationEngineService.cs
- src/SIL.Machine.AspNetCore/Services/NmtClearMLBuildJobFactory.cs
- src/SIL.Machine.AspNetCore/Services/NmtEngineService.cs
- src/SIL.Machine.AspNetCore/Services/NmtHangfireBuildJobFactory.cs
- src/SIL.Machine.AspNetCore/Services/NmtPostprocessBuildJob.cs
- src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs
- src/SIL.Machine.AspNetCore/Services/NmtTrainBuildJob.cs
- src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs
- src/SIL.Machine.AspNetCore/Services/SmtTransferBuildJob.cs
- src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs
- src/SIL.Machine.AspNetCore/Services/SmtTransferHangfireBuildJobFactory.cs
- tests/SIL.Machine.AspNetCore.Tests/Services/ClearMLServiceTests.cs
- tests/SIL.Machine.AspNetCore.Tests/Services/NmtEngineServiceTests.cs
- tests/SIL.Machine.AspNetCore.Tests/Services/SmtTransferEngineServiceTests.cs
See [here](https://github.com/sillsdev/machine/pull/104) for previous discussion.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/109)
> Config passing via build options for post-nmt/hangfire refactor

- src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/112)
> Working percent completed

- .github/workflows/ci-e2e.yml
Fixes https://github.com/sillsdev/serval/issues/158
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/116)
> Separate repos in e2e tests

- src/SIL.Machine.AspNetCore/Services/NmtClearMLBuildJobFactory.cs
- tests/SIL.Machine.AspNetCore.Tests/Services/NmtClearMLBuildJobFactoryTests.cs
- properly handle languages with an implicit script
- normalize Chinese subtags
- convert macrolanguage subtag to corresponding standard language subtag
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/123)
> Make lang tag to NLLB lang code conversion more robust

- .github/workflows/ci-e2e.yml
Fixes https://github.com/sillsdev/serval/issues/153
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/127)
> Parallel e2e tests

- src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/129)
> Fixes #128

- src/SIL.Machine.AspNetCore/Models/Corpus.cs
- src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs
- src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs
See parallel PR: https://github.com/sillsdev/serval/pull/215
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/132)
> Fixes https://github.com/sillsdev/serval/issues/202

- src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs
Fixes https://github.com/sillsdev/serval/issues/212
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/137)
> Change front of queue to queueDepth = 1

- src/SIL.Machine.Translation.Thot/ThotWordAlignmentModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/139)
> Fix crash when loading Thot alignment model

- src/SIL.Machine.Translation.Thot/SIL.Machine.Translation.Thot.csproj
- src/SIL.Machine.Translation.Thot/Thot.cs
- use latest version of Thot
- fix memory leak when model doesn't load properly
- fixes #142
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/147)
> Make ThotSmtModel loading more robust

- src/SIL.Machine.AspNetCore/SIL.Machine.AspNetCore.csproj
- src/SIL.Machine.AspNetCore/Services/ILanguageTagService.cs
- src/SIL.Machine.AspNetCore/Services/ITranslationEngineService.cs
- src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs
- src/SIL.Machine.AspNetCore/Services/NmtClearMLBuildJobFactory.cs
- src/SIL.Machine.AspNetCore/Services/NmtEngineService.cs
- src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs
- src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs
- src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs
- src/SIL.Machine.AspNetCore/data/flores200languages.csv
- tests/SIL.Machine.AspNetCore.Tests/Services/LanguageTagServiceTests.cs
- tests/SIL.Machine.AspNetCore.Tests/Services/NmtClearMLBuildJobFactoryTests.cs
- tests/SIL.Machine.AspNetCore.Tests/Services/NmtEngineServiceTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/159)
> Language endpoint

- src/SIL.Machine/Corpora/ParatextProjectSettings.cs
- src/SIL.Machine/Corpora/ZipParatextProjectSettingsParser.cs
- src/SIL.Machine/Corpora/ZipParatextProjectSettingsParserBase.cs
- tests/SIL.Machine.Tests/Corpora/ParatextProjectSettingsTests.cs
- add ParatextProjectSettings.GetBookFileName()
- add ZipParatextProjectSettingsParserBase class
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/163)
> Add functionality to Paratext project settings parser

- src/SIL.Machine.AspNetCore/Services/NmtEngineService.cs
- src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs
- src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs
- tests/SIL.Machine.AspNetCore.Tests/Services/NmtEngineServiceTests.cs
- tests/SIL.Machine.AspNetCore.Tests/Services/SmtTransferEngineServiceTests.cs
- fixes #162
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/165)
> Cancel build gRPC endpoint returns Aborted when no build is running

- src/SIL.Machine.AspNetCore/Models/ClearMLMetricsEvent.cs
[#332](https://github.com/sillsdev/serval/issues/332)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/175)
> fix ClearML Event error - only require fields used

- .github/workflows/ci-e2e.yml
- src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/178)
> Fix some logic found during e2e testing

- src/SIL.Machine/Corpora/ParatextProjectSettingsParserBase.cs
- tests/SIL.Machine.AspNetCore.Tests/Services/data/pt-target1/Settings.xml
See https://github.com/sillsdev/serval/issues/357.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/180)
> default to major biblical terms

- src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs
Fixes https://github.com/sillsdev/serval/issues/364
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/188)
> Allow for write commands that are greater than 5MB.

- src/AssemblyInfo.props
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/218)
> Update library version to 3.2.1

- src/SIL.Machine/Corpora/UsfmTokenizer.cs
- tests/SIL.Machine.Tests/Corpora/UsfmTokenizerTests.cs
This is to fix: https://github.com/sillsdev/serval/issues/424.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/220)
> USFM column index issue

- src/AssemblyInfo.props
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/221)
> Update to 3.2.2

- src/AssemblyInfo.props
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/223)
> release 3.2.3

- src/SIL.Machine/Corpora/ScriptureRefUsfmParserHandlerBase.cs
- src/SIL.Machine/Corpora/UsfmParser.cs
- src/SIL.Machine/Corpora/UsfmTextBase.cs
- tests/SIL.Machine.Tests/Corpora/UsfmMemoryTextTests.cs
https://github.com/sillsdev/serval/issues/424
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/224)
> Usfm nonverse multichapter

- src/AssemblyInfo.props
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/225)
> release 3.2.4

- src/SIL.Machine/Corpora/UsfmTextBase.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/230)
> Fix quotation mark in USFM parsing error message

- src/AssemblyInfo.props
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/231)
> Release 3.2.5

- src/AssemblyInfo.props
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/234)
> release 3.2.6

- src/SIL.Machine/Corpora/UsfmTextBase.cs
https://github.com/sillsdev/serval/issues/412
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/236)
> Call the horizontal position "character"

- src/SIL.Machine/Translation/IInteractiveTranslationModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/240)
> Add Save method to IInteractiveTranslationModel

- src/SIL.Machine/Corpora/BiblicalTermsId.xml
Fixes #244.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/246)
> Fix typo in localization xml

- src/AssemblyInfo.props
@Nateowami requested the last change ASAP.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/247)
> Update revision to 3.2.8

- src/AssemblyInfo.props
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/252)
> Update version to 3.3.0

- src/SIL.Machine/Corpora/UsxFileAlignmentCollection.cs
- src/SIL.Machine/Corpora/UsxMemoryText.cs
- src/SIL.Machine/Corpora/UsxToken.cs
- src/SIL.Machine/Corpora/UsxVerse.cs
- src/SIL.Machine/Corpora/UsxVerseParser.cs
- tests/SIL.Machine.Tests/Corpora/UsxMemoryTextTests.cs
Mirror of https://github.com/sillsdev/machine.py/pull/138
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/269)
> Add USX table and fix incorrect handling of descriptive titles

- src/AssemblyInfo.props
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/271)
> Update version to 3.4.2

- src/SIL.Machine/Corpora/NParallelTextCorpus.cs
- tests/SIL.Machine.Tests/Corpora/NParallelTextCorpusTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/275)
> Allow for zero corpora

- src/AssemblyInfo.props
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/289)
> Update version to 3.6.1

- src/AssemblyInfo.props
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/292)
> Update version to 3.6.2

- src/AssemblyInfo.props
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/293)
> release 3.6.3

- src/AssemblyInfo.props
- tests/SIL.Machine.Tests/Corpora/UpdateUsfmParserHandlerTests.cs
(Also removed a comment that was missed in an earlier PR).
This is needed for the next 1.9 candidate release to QA.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/300)
> Update to version 3.6.4

- src/AssemblyInfo.props
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/302)
> Update machine version to 3.6.5

- src/AssemblyInfo.props
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/309)
> Update version to 3.6.6

- src/AssemblyInfo.props
If you think `3.7.0` would be more appropriate, let me know, @ddaspit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/320)
> Update version to 3.6.8

- src/AssemblyInfo.props
- src/SIL.Machine/Corpora/UpdateUsfmParserHandler.cs
- tests/SIL.Machine.Tests/Corpora/UpdateUsfmParserHandlerTests.cs
I'll need to add a change to the machine.py PR to keep the behavior consistent. This is needed for the IDQ PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/321)
> Add remarks after existing remarks

- src/AssemblyInfo.props
This should be put in after https://github.com/sillsdev/machine/pull/344
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine/346)
> Update library version to 3.7.6
